### ISSUE TITLE
Could not find module in path: 'is-dev'

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#12]
Hey Alec, nice work! I've been playing around with this and first impressions it seems significantly more performant than mobx. However, I've been using version 0.6 because higher versions get the following error `Could not find module in path: 'is-dev' relative to '/node_modules/wana/dist/wana.cjs.js'`. Would be possible to take a look when you get a moment?

It also looks like it's possible to used `derived` outside of react, in the following way. Is that correct?
```js
import { o, derived, auto } from 'wana'
let count = o(1);
const multiplied = derived(() => count * 10, [count])
  auto(() => {
    console.log('multiplied:', multiplied())
  })
```

**Comment by aleclarson** [comment]
Hmm, a minimal repro would help a lot here. The dependency is definitely installed:
https://github.com/alloc/wana/blob/c74c85c8d7ba0ce8d72a0ce65cfa14faa6e389cd/package.json#L30

Note: I plan to write a Babel plugin that replaces `isDev` with something like `process.env.NODE_ENV !== 'production'` so bundlers can tree shake those blocks.

> It also looks like it's possible to used `derived` outside of react, in the following way. Is that correct?

You can create an observable getter using the `o` function:
```ts
const state = o({ count: 1 })
const multiplied = o(() => state.count * 10)
const observer = auto(() => console.log('multiplied:', multiplied()))
state.count++

// To release memory and stop observing:
multiplied.dispose()
observer.dispose()
```

A few things to notice here:
- Wrapping a primitive value with `o` does nothing. Only objects can be observable :)
- When using `o` instead of `useDerived`, there is no deps argument
- Be sure to call `dispose` before dereferencing both `multiplied` and `observer`

Thanks for checking out `wana` 👍

**Comment by aleclarson** [comment]
Oh you might need to update npm (or use yarn/pnpm).

https://twitter.com/koste4/status/1195422295562620929

**Comment by ryanking1809** [comment]
> Hmm, a minimal repro would help a lot here
Perhaps it's a codesandbox issue? https://codesandbox.io/s/goofy-morning-ds2fo

> Wrapping a primitive value with o does nothing. Only objects can be observable :)
That explains some other issues I've been having!

So functions within an object will work the same way? If I had a class like the following, will `get multiplier()` become an observable getter?
```js
class Count {
    val = 1
    get multiplier() {
        return this.val * 10
    }
}
const oCount = o(Count())
```

**Comment by aleclarson** [comment]
> If I had a class like the following, will `get multiplier()` become an observable getter?

No, because it would need a way to dispose the getter's observer.

The workaround could probably be made into a helper class though:
```js
const $getters = Symbol.for('Observable.getters')

export class Observable {
  constructor() {
    const keys = findGetters(this.constructor)
    keys.forEach(key => {
      this[key] = o(this[key])
    })
    this[$getters] = keys
    return o(this)
  }
  dispose() {
    this[$getters].forEach(key => this[key].dispose())
  }
}

function findGetters(ctr) {
  // TODO: crawl prototype chain looking for getters
}
```

**Comment by aleclarson** [comment]
You might want to make the `Observable` class wrap methods with `noto` too, which would prevent callers from accidentally observing any state used inside each method.

**Comment by aleclarson** [comment]
> Perhaps it's a codesandbox issue? [codesandbox.io/s/goofy-morning-ds2fo](https://codesandbox.io/s/goofy-morning-ds2fo)

My guess is that CodeSandbox still uses an npm version older than 6.9.0

I'll stop using an alias for now :)

**Comment by aleclarson** [comment]
Fixed in v0.10.1

**Comment by ryanking1809** [comment]
Thanks Alec, I'll have more of a play!

**Comment by aleclarson** [comment]
I made a sandbox with my code above. The `Observable` class is so nice that I'm thinking of including it by default. :)

https://codesandbox.io/s/wana-observable-class-9142q

**Comment by ryanking1809** [comment]
I just had a play and it's very nice! Should make it much easier to replace my mobx classes.

Some thoughts on the api: 
I get that you're not extending primitives in order to avoid creating classes to wrap them, but there's something nice about how in mobx you explicitly define what is observable and what isn't, and there's something odd here about how some datatypes are automatically observable and others aren't.

I'm wondering if you had an api like this and put the observer stuff in the parent object?
```js
class Store {
  value = o(12345);
  o(get doubleVal() { // I'm not sure you can wrap a getter like this
    this.value *2
  })
  objects = o([]);
  objectIds = o(new Set());
}
```

Whereas this exist approach some things are automaticcally observable and others aren't. 
Perhaps it'll be a point of confusion?
```js
class Store extends Observable {
  value = 12345;
  get doubleVal() {
    this.value *2
  }
  objects = o([]);
  objectIds = o(new Set());
}
```
I understand how this may also conflict with the existing api - but some food for thought!

Either way, I really like programming with observables, but the existing libraries are a bit too sluggish three.js work I'm doing - and from what I can tell so far, wana will be a very nice fit :) Thanks for the work you put into it!

**Comment by aleclarson** [comment]
As far as confusion is concerned, the docs could probably do a better job at explaining how observability is thought of in wana.

Sets and arrays are **atomic** in that you can only observe the entire object. For everything else, it's the **keys** that are observable, **not** the values. Shallow observability is the default because it's easier to opt-in to deep observation than it is to opt-out. It also encourages keeping your models flat. And personally, I don't mind the explicitness.

It probably wouldn't be hard to create a "proxy factory" that wraps nested object values with `o` whenever they're accessed. Might even be worth including in wana core.

> Either way, I really like programming with observables, but the existing libraries are a bit too sluggish three.js work I'm doing. From what I can tell so far, wana will be a very nice fit :) Thanks for the work you put into it!

Good to hear! Keep the feedback coming ;)

**Comment by ryanking1809** [comment]
Hey Alec, bit confused by this example in the docs
```js
const state = o({
  count: 1,
})

const increment = no((n: number) => {
  state.count = state.count + n
})

auto(() => {
  increment(1) // Nothing will be observed in here.
})
```

Why does increment need to be wrapped in `no`? What would happen if it isn't wrapped in `no`? Can `auto` see that `increment` uses observable values inside the function?

Maybe I can help tweak the docs a little once I wrapp my head around things :)

**Comment by aleclarson** [comment]
> It probably wouldn't be hard to create a "proxy factory" that wraps nested object values with `o` whenever they're accessed. Might even be worth including in wana core.

So this turned out to be really straight forward. :)

https://codesandbox.io/s/wana-deepobservable-class-qiz1z (see `DeepObservable.js`)


> Why does increment need to be wrapped in `no`? What would happen if it isn't wrapped in `no`? Can `auto` see that `increment` uses observable values inside the function?

The `no` function is short for "non-observable". When you pass a function, it gets wrapped in `noto` to prevent the caller from observing anything done inside your function. The intended use case is for calling side effects inside an observer. If you don't want to wrap your function with `no` before calling it, you can instead wrap your callsite with `noto` like this:
```ts
const increment = (n: number) => (state.count += n)

auto(() => {
  // "noto" calls your function immediately, 
  // and "auto" can't observe anything in there
  noto(() => increment(1))
  // The line above is identical to:
  no(increment)(1)
})
```
Admittedly, it's not a practical example, so I totally understand the confusion.



> Should I be wrapping the increment function here? https://codesandbox.io/s/wana-observable-class-mkmi8

Looks like you forgot to save?



> Maybe I can help tweak the docs a little once I wrapp my head around things :)

Sure thing! PRs welcome :)

**Comment by ryanking1809** [comment]
So this is observable eventhough I never wrapped it in a `o()` function()?
```js
const increment = (n: number) => (state.count += n)
```
I think maybe I'm just getting confused as the example isn't a practical example. It just makes me worried that the increment function on the example below will have knock effects I'm not ware of.

> > Should I be wrapping the increment function here? https://codesandbox.io/s/wana-observable-class-mkmi8
> Looks like you forgot to save?
Maybe try now. The class has an `increment` function, where as before you were doing it outside the class.

**Comment by ryanking1809** [comment]
> So this turned out to be really straight forward. :)
>https://codesandbox.io/s/wana-deepobservable-class-qiz1z (see DeepObservable.js)

Looks awesome but I think I wasn't clear in the above post. Automatic deep observables scare me a little bit, but I'm sure there'll be a lot of people who'll love it. I was just more sugesting maybe it would be nicer to explicitly say what primitives are observable inside an object. Sorry for the confusion!

**Comment by aleclarson** [comment]
> So this is observable eventhough I never wrapped it in a `o()` function()?

The `state.count += n` part can be observed because `state` (which is observable) has its `count` property accessed. It's more obvious when you expand it to `state.count = state.count + n`.

If you only did `state.count = n`, nothing in `state` would be *accessed*, so nothing would be observable.

> Maybe try now. The class has an `increment` function, where as before you were doing it outside the class.

In that case, you wouldn't *need* to wrap `increment` with `no` unless you're calling it from within an observer (eg: an `auto` callback) that you don't want to observe `this.val`. Why wouldn't you want `this.val` to be observed? Because `increment` is intended to be a side effect.

> Looks awesome but I think I wasn't clear in the above post. Automatic deep observables scare me a little bit, but I'm sure there'll be a lot of people who'll love it. I was just more sugesting maybe it would be nicer to explicitly say what primitives are observable inside an object (ie. nothing inside an object is observable unless I say so). Quite the opposite haha, sorry for the confusion!

Ah I see. That wouldn't be impossible, but I've never really needed a non-observable property inside an observable object. As long as you think of them as "observable properties" instead of "observable primitives", the mental model shouldn't be confusing.

**Comment by ryanking1809** [comment]
> In that case, you wouldn't need to wrap increment with no unless you're calling it from within an observer (eg: an auto callback) that you don't want to observe this.val. Why wouldn't you want this.val to be observed? Because increment is intended to be a side effect.

Ok go it! I didn't `auto()` would observe the observables inside a function. Thanks :)

> Ah I see. That wouldn't be impossible, but I've never really needed a non-observable property inside an observable object. As long as you think of them as "observable properties" instead of "observable primitives", the mental model shouldn't be confusing.

All good, come to think it I'm not sure of a use case either. It's just what I'm use to from mobx.

**Comment by ryanking1809** [comment]
It's still a little rough but I've modified the observer class so that all getter functions are automatically observable but all others are expected to be side effects and protected with `noto()` (perhaps it's a common use case?). It seems to be working fine. I'm not sure if you can see any issues here? Do you need to dispose a `noto()`?
https://codesandbox.io/s/wana-observable-class-mkmi8

```js
import { o, no, noto } from "wana";

const $getters = Symbol.for("Observable.getters");
const $funcs = Symbol.for("Observable.funcs"); // learn what this is

export class Observable {
  constructor() {
    this[$getters] = [];
    this[$funcs] = [];
    findGetters(this).forEach((get, key) => {
      get = o(get.bind(o(this)));
      Object.defineProperty(this, key, { get });
      this[$getters].push(get);
    });
    findFuncs(this).forEach((value, key) => {
      value = noto(() => value);
      Object.defineProperty(this, key, { value });
      this[$funcs].push(value);
    });
    return o(this);
  }
  dispose() {
    this[$getters].forEach(getter => getter.dispose());
    this[$funcs].forEach(fun => func.dispose());
  }
}

function findGetters(instance) {
  const getters = new Map();
  let proto = instance.constructor.prototype;
  while (proto) {
    const props = Object.getOwnPropertyDescriptors(proto);
    for (const key in props) {
      if (key === "__proto__") continue;
      if (!getters.has(key) && props[key].get) {
        getters.set(key, props[key].get);
      }
    }
    proto = proto.__proto__;
  }
  return getters;
}

function findFuncs(instance) {
  const funcs = new Map();
  let proto = instance.constructor.prototype;
  while (proto) {
    const props = Object.getOwnPropertyDescriptors(proto);
    for (const key in props) {
      if (key[0] === "_") continue;
      if (funcBlacklist.includes(key)) continue;
      if (!funcs.has(key) && typeof props[key].value === "function") {
        funcs.set(key, props[key].value);
      }
    }
    proto = proto.__proto__;
  }
  return funcs;
}

const funcBlacklist = [
  "constructor",
  "dispose",
  "hasOwnProperty",
  "propertyIsEnumerable",
  "isPrototypeOf",
  "toString",
  "valueOf",
  "toLocaleString"
];

```

**Comment by aleclarson** [comment]
> Do you need to dispose a `noto()`?

Nope, only observers need to be disposed.

> It seems to be working fine. I'm not sure if you can see any issues here?

You're using `noto` incorrectly. It only prevents observation within the callback, so you want to call `value` in there. A better solution is to use the `no` function:

```js
value = no(value.bind(this))
```

In the future, I might experiment with using prototype proxies for on-demand binding (to avoid binding every method to every instance). Although, it's probably not that big of a deal.

**Comment by ryanking1809** [comment]
Oh I tried `value = no(value.bind(this))` and it didn't work. I'll take another look!

**Comment by aleclarson** [comment]
My bad, you need to do `o(this)` before binding:

```ts
value = no(value.bind(o(this)))
```

**Comment by ryanking1809** [comment]
That does the trick! Thanks for your help!

**Comment by ryanking1809** [comment]
Hey Alec, any idea why the set (`count.values`) isn't being logged with `auto` here? Perhaps it's because I'm running `no()` on setters? (if I don't, setters break) But from what I understand that shouldn't matter? Maybe I should be using your DeepObservable class afterall..

https://codesandbox.io/s/wana-observable-class-mkmi8

**Comment by aleclarson** [comment]
> any idea why the set (`count.values`) isn't being logged with `auto` here?

When you access a property of an observable object, you're only observing the property, not the value. To observe the entire nested `Set` object, you can call one of its methods (eg: `forEach`) or you can pass it to `Array.from` (which wana carefully overrides).

> Edit: Using your DeepObservable Class to extend my Observable class does seem to work (I might actually start using it - I didn't realise it only went 1 level deep). But I'm not sure what's happening diferently compared to the code above.

Yup, you wouldn't want to add deep observability to nested objects without their permission. :)

**Comment by ryanking1809** [comment]
Oh that makes sense. Thankyou!

**Comment by ryanking1809** [comment]
Ok, there's one last thing I don't understand. Why doesn't `store.array[0]` work in an auto if I set `store.array[0] = 10`. They're pointing to the same reference and the value has changed. It looks like in need to create a new array with `Array.from` everytime I want to observe any array value whether it's the entire array or just a particular index, is that correct?

https://codesandbox.io/s/wana-deepobservable-class-27dz3

**Comment by aleclarson** [comment]
From [this comment](https://github.com/alloc/wana/issues/12#issuecomment-554602611) further up this thread:

> arrays are **atomic** in that you can only observe the entire object

Is there a particular use case where you'd **need** to observe an array index? I haven't needed it in my apps, and considering the volatile nature of arrays, I wouldn't recommend it.

**Comment by ryanking1809** [comment]
Sorry should have re-read the thread!  Thanks :)
Yes, this actually emerged from me hacking some stuff together. I don't think it's required in the final product. It's just something I didn't understand, and to keep in mind as I build things out.

**Comment by aleclarson** [comment]
No prob. I'm gonna lock this thread so other curious people can find your future questions via search. :)
