### ISSUE TITLE
Maintaining Caret Position with Input Fields

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#14]
Hey Alec, when using `withAuto` with input fields react seems to loose the caret position, when typing in a new value. 

I can fix it be replicating the state locally, I need to be able to set the input value from both inside and outside the input component (represented by the 'generate number' button). 

And again adding `useState` to a shared parent would fix it in this example, but I need to use external state due to things being update outside of react. Is it possible to retain the caret position when updating from global state?

How the input should behave (but using local state):
https://codesandbox.io/s/friendly-hill-5ebqw

Wana example using external state, but the caret jumps to the end on input:
https://codesandbox.io/s/eager-black-l51dn

**Comment by ryanking1809** [comment]
Sorry I don't think this is related to `wana` https://github.com/facebook/react/issues/955

I've managed to get something messy working using focus / blur to determin when to use local or global state. https://codesandbox.io/s/vibrant-almeida-694cg

```jsx
const state = o({ number: Math.random() * 100 });
const setNumber = val => (state.number = val);
const App = withAuto(() => {
  return (
    <div className="App">
      <InputComponent />
      <button onClick={e => setNumber(Math.random() * 100)}>
        Generate Number
      </button>
    </div>
  );
});

const InputComponent = withAuto(() => {
  const [inputVal, setInputVal] = useState(state.number);
  const [isFocussed, setIsFocussed] = useState(false);
  useEffect(() => {
    if (!isFocussed) {
      setInputVal(state.number);
    }
  });
  const handleChange = e => {
    if (isFocussed) {
      setInputVal(e.target.value);
    }
    setNumber(e.target.value);
  };
  return (
    <input
      onFocus={() => setIsFocussed(true)}
      onBlur={() => setIsFocussed(false)}
      value={inputVal}
      onChange={handleChange}
    />
  );
});
```

**Comment by aleclarson** [comment]
Huh, I never knew about this quirk in React. Thanks!

Maybe wana could have its own `input` primitive in the future that works around this.

**Comment by ryanking1809** [comment]
YeahI never noticed before but turns out mobx avoids it somehow https://codesandbox.io/s/quirky-mestorf-1dx32  - maybe it can be built into withAuto

**Comment by aleclarson** [comment]
> maybe it has something to do with how `withAuto` references state?

Nope, the reason is that mobx reactions are always synchronous, while wana uses microtasks (the same mechanism used by promises) for implicit batching.

**Comment by ryanking1809** [comment]
Right, I'll have to read up on how they work!

**Comment by aleclarson** [comment]
Here's a great article on it: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by ryanking1809** [comment]
Thanks, I'll take a look!
