### ISSUE TITLE
Watch a single property without "auto"

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#15]
Is there a way to apply `watch` just to specific object key rather than the whole object?
I have a large observable state, and need to trigger some side effect when certain properties change. The side effect doesn't use the object I'm watching so I can't use `auto`, and `watch` on the whole state will cause the side effect to fire unnecessarily.

A simple example below, is it possible to log `"side effect"` to the console when `count` changes but not when `number` changes?
https://codesandbox.io/s/serene-frog-5uige

```jsx
const state = o({
  count: 0,
  number: 0
});
watch(state.count, () => console.log("unrelated side effect"));

function App() {
  return (
    <div className="App">
      <button onClick={() => state.count++}>Count ++</button>
      <button onClick={() => state.number--}>Number --</button>
    </div>
  );
}
```

EDIT: Perhaps the best way is to just to reference the value in `auto` and never use it?
```js
auto(() => {
  const watch = state.count;
  console.log("unrelated side effect")
})
```

**Comment by aleclarson** [comment]
Yeah, `auto` should work fine, but I imagine the unused expression could confuse others (if you work on a team) when debugging your code.

I wrote up this helper function that should do the job:

```ts
import { Change, ChangeObserver, $O } from 'wana'

/** Watch a specific key of an observable `Map` for changes */
export function onChange<K, V>(
  target: Map<K, V>,
  key: K,
  onChange: (change: Change<V>) => void
): ChangeObserver

/** Watch a specific key of an observable object for changes */
export function onChange<T extends object, P extends keyof T>(
  target: T,
  key: P,
  onChange: (change: Change<T[P]>) => void
): ChangeObserver

export function onChange(target:object, key: any, onChange: (change: Change) => void) {
  const observable = target[$O]
  if (!observable) {
    throw Error('Expected an observable object')
  }
  const observers = observable.get(key)
  const observer: ChangeObserver = {
    onChange,
    dispose: () => observers.delete(observer),
  }
  observers.add(observer)
  return observer
}
```

I might include it in the official API at some point, but I would need to settle on the name and capabilities first.

Here's an example of it action:
```ts
import { o } from 'wana'
import { onChange } from './onChange'

const foo = o({ count: 0 })
const observer = onChange(foo, 'count', change => {
  // Nothing is ever observed in here.
})

// Also works with Map objects:
const map = new Map()
const observer = onChange(map, foo, change => {
  console.log(change)
})
map.set(foo, true)
map.clear()
```

**Comment by ryanking1809** [comment]
I don't work with a team yet, but could be hepful in the future, thanks! (even if re-reading my own code). 

I might try to tweak it so it an optionally accept an array. That will also cover the syntax I was suggesting with `auto`. It does create more maintenance but also offers more strict control (I keep forgetting to wrap things in `no` and am creating unecessary reactions)

**Comment by aleclarson** [comment]
> I might try to tweak it so it an optionally accept an array.

Just remember that indices can't be observed individually. ;) Though, you could add support for observing the entire array. To do that, you would pass `$O` to `observable.get` instead of the `key` argument.

**Comment by ryanking1809** [comment]
Oh I meant an array of properties to react to.
eg. (perhaps a better syntax)

```js
const state = o({ count: 0, foo: 0, bar: 0 })
const observer = onChange([[state, 'foo'], [state, 'bar'], change => {
  // Nothing is ever observed in here.
})
```

**Comment by aleclarson** [comment]
You can now use `watch` to observe a single property. Just note that if the property points to an observable object, that entire object will also be observed.
```ts
import { watch } from 'wana'

const watcher = watch(state, 'count', change => {
  console.log('new count:', change.value)
})

watcher.dispose()
```
