### ISSUE TITLE
Safari - TypeError: Map operation called on non-Map object

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#16]
Hey Alec, have you hit this error in Safari (13.1) before?
`TypeError: Map operation called on non-Map object`

I'm still trying to find a replicable example. It works flawlessly in Chrome and Firefox, and every time I think I pinpoint the issue, it pops up somewhere else with a very different stack trace.

I'll keep trying to figure out what's going on, but thought I'd touch base to see if you've come across it? I have a feeling it's those Observable / AutoObservable classes we set up before - doesn't help that Safari's dev tools are a nightmare to use.

**Comment by ryanking1809** [comment]
Ok I think I've figured it out https://codesandbox.io/s/nervous-sammet-x7ipb?file=/src/SubStore.js

The sandbox above works in chrome but not safari. I don't get the error above with the latest release but I do with `0.10.3`. The issue appears to be in `AutoObservable`. In particular, I think it's trying to observe a class property with `o()` that has already had `o()` applied, effectively `o(o(classProp))`. And maybe safari doesn't like proxies of proxies?

Is there a way to identify if an object is already an observable? Should fix the issue.

**Comment by aleclarson** [comment]
> I think it's trying to observe a class property with `o()` that has already had `o()` applied, effectively `o(o(classProp))`.

The `o` function reuses the observable proxy when possible, so I don't think that's it.

**Comment by aleclarson** [comment]
Okay, I figured it out. Apply this patch, which avoids wrapping an `AutoObservable` proxy with the `o` function:
```diff
diff --git a/src/AutoObservable.js b/src/AutoObservable.js
old mode 100755
new mode 100644
index 4e32f89..d0bd7fe
--- a/src/AutoObservable.js
+++ b/src/AutoObservable.js
@@ -1,15 +1,18 @@
 import { Observable } from "./Observable";
 import { o } from "wana";
 
+const $A = Symbol('AutoObservable')
+
 export class AutoObservable extends Observable {
   constructor() {
     super();
     return new Proxy(this, {
       get: (target, key) => {
+        if (key == $A) return true;
         // Only wrap direct properties.
         if (Object.getOwnPropertyDescriptor(target, key)) {
           const val = target[key];
-          return typeof val !== "function" ? o(val) : val;
+          return !val[$A] && typeof val !== "function" ? o(val) : val;
         }
         return target[key];
       }
```

**Comment by aleclarson** [comment]
Oh, it should probably check for `val && !val[$A]` in case the value is undefined or whatever.

**Comment by ryanking1809** [comment]
Omg sourcemap support in safari is fucked, I had to slowly comment out bits of code to pinpoint the issue. Thanks for your help, this certainly does the trick!
