### ISSUE TITLE
Event history

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#17]
Hi Alec, does wana have a central event system I can spy on like with mobx? https://mobx.js.org/refguide/spy.html

I need to build an undo system and it would be nice to just filter the existing observable events if possible. It's not a huge deal putting in the extra labour otherwise.

ps. I tried switching to mobx to test this out and all my animations became slow and choppy. Maybe it's my bad code but wana is significantly faster, good work!

**Comment by aleclarson** [comment]
This oughta do the trick: #18 WDYT?

> ps. I tried switching to mobx to test this out and all my animations became slow and choppy. Maybe it's my bad code but wana is significantly faster, good work!

🔥🔥🔥 

All without any effort on my part. 😆 I wonder what `mobx` is doing that `wana` isn't. 🤔

**Comment by ryanking1809** [comment]
Yeah, that should do it (I think), thanks!

It seems as though reading the observable values in mobx is slower, and it really adds up on the animations - or maybe it seems to be making longer chains of getters which is slowing things down.

**Comment by aleclarson** [comment]
Released in `v0.11.4` 🎉

**Comment by ryanking1809** [comment]
🙌

**Comment by ryanking1809** [comment]
Hey Alec, this is exactly what I need, thanks! Any idea why each event fires twice though?
https://codesandbox.io/s/magical-sunset-hjbww?file=/src/App.js

**Comment by aleclarson** [comment]
lol good question. I admit I neglected to test it 😅

**Comment by aleclarson** [comment]
Ok, fixed in `v0.11.5` 🚀

**Comment by ryanking1809** [comment]
Perfect thanks!
