### ISSUE TITLE
Illegal invocation in codesandbox

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#19]
This seems to only be a codesandbox issue from what I can tell, so no emergency. 
Any idea why this is causing and illegal invocation?
https://codesandbox.io/s/wana-tests-oo5lo?file=/src/App.js

**Comment by ryanking1809** [comment]
seemed to be an issue with an unused file

**Comment by aleclarson** [comment]
Seems like CodeSandbox is compiling the ESM bundle without `export default`/`module.exports` interop. 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/1925840/84213305-4a7ceb00-aa8e-11ea-9a1a-8f46de5bd15a.png)

**Comment by ryanking1809** [comment]
I see, will let them know, thanks!
