### ISSUE TITLE
globals.beforeChange

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#22]
Hey Alec, trying to implement undo / redo. I think I can get something hacked together with global `beforeChange` event. Would that be possible?

The rough idea is to create a localized history by listening to observables using `auto`. But I need to somehow get the event object into the localized history when something changes. Using `beforeChange`, I think I can record all change events, then after, the `auto` function can just grab the latest event off the stack.

**Comment by aleclarson** [comment]
Released #23 in v0.13.0 🎉
