### ISSUE TITLE
Auto failing with observable getters

### ISSUE THREAD

**Issue by ryanking1809** [alloc/wana#25]
Auto should fire when `stringObj.string` is updated right?

https://codesandbox.io/s/wana-auto-getters-rub4s?file=/src/App.js

```js
const stringObj = o({string: "124"})
const numObj = o(() => parseFloat(stringObj.string));
auto(() => console.log("number", numObj()), {sync: true})

// nothing happens here
stringObj.string = "111"
```

Edit: Went back a few versions. Looks like it broke with the getter update on `0.12.7`
`0.12.6` works as expected.

**Comment by aleclarson** [comment]
Whoops, I never tested sync `auto` using a derived value. 😅 

🎉Fixed by 6c9648f1ad1177c28a30c29233260dfee37c8b23 in `v0.13.3`

**Comment by ryanking1809** [comment]
Awesome thanks!

**Comment by ryanking1809** [comment]
Wait, should this also work?

```js
const stringObj2 = o({ string: "432" });
const numObj2 = o(() => o({ num: parseFloat(stringObj2.string) }));
auto(() => console.log("number", numObj2().num), { sync: true });
// nothing happens here
stringObj.string = "222";
```

**Comment by aleclarson** [comment]
Should be `stringObj2.string = ...`

**Comment by ryanking1809** [comment]
Yes, sorry! Thanks!

**Comment by ryanking1809** [comment]
🤔 There is still something somewhere in `0.13.3` that breaks when I turn sync on. Hopefully, I can pinpoint it tomorrow...
